# Generated by Django 4.2.20 on 2025-03-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_ride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
