# Generated by Django 4.2.20 on 2025-03-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_ride_current_latitude_ride_current_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='current_latitude',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='current_longitude',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
